###
POST http://localhost:3001/register
Content-Type: application/json 

{
  "username": "madhavi",
  "password": "madhavi",
  "name": "madhavi",
  "gender": "female"
}

###
POST http://localhost:3001/login
Content-Type: application/json 

{
  "username": "madhavi",
  "password": "madhavi",
}

###
POST http://localhost:3001/userdetails/
Content-Type: application/json 

{
    "jwtToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmF5IiwiaWF0IjoxNjM2NjI3NDQ1fQ.lr-6f-8iYkjFQ0FySrdzBbNbrYm2MlvjgMfVFqUm-50"
}

###
GET http://localhost:3001/idp-tracks/